# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [4]:
print(np.version)
print(np.show_config)


<module 'numpy.version' from 'c:\\Users\\gkahl\\anaconda3\\Lib\\site-packages\\numpy\\version.py'>
<function show_config at 0x000002029153E340>


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [ ]:
a = np.random.random((2, 3, 5))
"""
# Variant 2:
a = []
for i in range(2):
    for j in range(3):
        a.append(np.random.random(5))

a = np.array(a)

# Variant 3:
a = np.array([
    [np.random.random(5) for j in range(3)]
    for i in range(2)
])
"""

'\na = []\nfor i in range(2):\n    for j in range(3):\n        a.append(np.random.random(5))\n\na = np.array(a)\n'


### 4. Print a.


In [12]:
### [your code here]
print(a)

[[[0.66782798 0.53417493 0.07404606 0.37779047 0.2492045 ]
  [0.68489842 0.21725795 0.65892524 0.08211679 0.16776245]
  [0.68232839 0.28329256 0.56821522 0.35461597 0.48399507]]

 [[0.45003929 0.72171265 0.66843085 0.04666762 0.0350458 ]
  [0.79939465 0.46330111 0.70133667 0.35215399 0.2728403 ]
  [0.24603653 0.23609903 0.00803577 0.19206598 0.45385346]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [ ]:
b = np.ones((5, 2, 3))

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 6. Print b.


In [15]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [17]:
if np.size(a) == np.size(b):
    print("They are the same size.")
else:
    print("They're not the same size.")

They are the same size.



### 8. Are you able to add a and b? Why or why not?


In [21]:
# No, at least not without reshaping as the dimensions need to match exactly.
a + b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [22]:
c = b.reshape(2,3,5)
print(a+c)

[[[1.66782798 1.53417493 1.07404606 1.37779047 1.2492045 ]
  [1.68489842 1.21725795 1.65892524 1.08211679 1.16776245]
  [1.68232839 1.28329256 1.56821522 1.35461597 1.48399507]]

 [[1.45003929 1.72171265 1.66843085 1.04666762 1.0350458 ]
  [1.79939465 1.46330111 1.70133667 1.35215399 1.2728403 ]
  [1.24603653 1.23609903 1.00803577 1.19206598 1.45385346]]]



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [ ]:
d = a + c
# It now works because the dimensions match exactly


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [ ]:
print(a)
print(d)
# They are the same except that d arises out of a by adding "1" onto every single value in a.


[[[0.66782798 0.53417493 0.07404606 0.37779047 0.2492045 ]
  [0.68489842 0.21725795 0.65892524 0.08211679 0.16776245]
  [0.68232839 0.28329256 0.56821522 0.35461597 0.48399507]]

 [[0.45003929 0.72171265 0.66843085 0.04666762 0.0350458 ]
  [0.79939465 0.46330111 0.70133667 0.35215399 0.2728403 ]
  [0.24603653 0.23609903 0.00803577 0.19206598 0.45385346]]]
[[[1.66782798 1.53417493 1.07404606 1.37779047 1.2492045 ]
  [1.68489842 1.21725795 1.65892524 1.08211679 1.16776245]
  [1.68232839 1.28329256 1.56821522 1.35461597 1.48399507]]

 [[1.45003929 1.72171265 1.66843085 1.04666762 1.0350458 ]
  [1.79939465 1.46330111 1.70133667 1.35215399 1.2728403 ]
  [1.24603653 1.23609903 1.00803577 1.19206598 1.45385346]]]



### 12. Multiply a and c. Assign the result to e.


In [25]:
e = a * c


In [32]:
print(e)
print(a)

[[[0.66782798 0.53417493 0.07404606 0.37779047 0.2492045 ]
  [0.68489842 0.21725795 0.65892524 0.08211679 0.16776245]
  [0.68232839 0.28329256 0.56821522 0.35461597 0.48399507]]

 [[0.45003929 0.72171265 0.66843085 0.04666762 0.0350458 ]
  [0.79939465 0.46330111 0.70133667 0.35215399 0.2728403 ]
  [0.24603653 0.23609903 0.00803577 0.19206598 0.45385346]]]
[[[0.66782798 0.53417493 0.07404606 0.37779047 0.2492045 ]
  [0.68489842 0.21725795 0.65892524 0.08211679 0.16776245]
  [0.68232839 0.28329256 0.56821522 0.35461597 0.48399507]]

 [[0.45003929 0.72171265 0.66843085 0.04666762 0.0350458 ]
  [0.79939465 0.46330111 0.70133667 0.35215399 0.2728403 ]
  [0.24603653 0.23609903 0.00803577 0.19206598 0.45385346]]]




### 13. Does e equal to a? Why or why not?


In [33]:
# Yes they are equal because "*" in NumPy signifies elementwise multiplication. 



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [35]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(d_max, d_min, d_mean)


1.7993946473206446 1.0080357674492855 1.3911155236307984



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [41]:
f = np.empty((2,3,5))
f[(0,0,1)]

np.float64(0.534174932144944)




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [45]:
for i in range(2):
    for j in range(3):
        for k in range(5):
            if d[(i,j,k)] > d_min and d[(i,j,k)] < d_mean:
                f[(i,j,k)] = 25





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [50]:
print("\nArray d:")
print(np.round(d,3))
print("Array f:")
print(np.round(f,3))


Array d:
[[[1.668 1.534 1.074 1.378 1.249]
  [1.685 1.217 1.659 1.082 1.168]
  [1.682 1.283 1.568 1.355 1.484]]

 [[1.45  1.722 1.668 1.047 1.035]
  [1.799 1.463 1.701 1.352 1.273]
  [1.246 1.236 1.008 1.192 1.454]]]
Array f:
[[[6.68e-01 5.34e-01 2.50e+01 2.50e+01 2.50e+01]
  [6.85e-01 2.50e+01 6.59e-01 2.50e+01 2.50e+01]
  [6.82e-01 2.50e+01 5.68e-01 2.50e+01 4.84e-01]]

 [[4.50e-01 7.22e-01 6.68e-01 2.50e+01 2.50e+01]
  [7.99e-01 4.63e-01 7.01e-01 2.50e+01 2.50e+01]
  [2.50e+01 2.50e+01 8.00e-03 2.50e+01 4.54e-01]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [54]:
g = [[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]]
print(g)

[[['D', 'D', 'D', 'B', 'D'], ['D', 'D', 'B', 'B', 'B'], ['D', 'B', 'D', 'D', 'D']], [['B', 'B', 'B', 'B', 'E'], ['D', 'D', 'D', 'D', 'D'], ['B', 'D', 'A', 'D', 'D']]]
